//------------------------------------------------------------------------------
// <auto-generated>
//     This file accompanies BusinessDataModel.edmx. The main context is defined
//     in BusinessDataModel.Context.cs.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    public partial class BusinessContext
    {
    }
}
